name: Web

on:
  push:
    branches: ["main"]
    paths:
      - "skyscrapers-web/**"
      - "skyscrapers-player/**"
      - "skyscrapers-generator/**"
      - "skyscrapers-core/**"
      - "skyscrapers-solver/**"
  pull_request:
    branches: ["main"]
    paths:
      - "skyscrapers-web/**"
      - "skyscrapers-player/**"
      - "skyscrapers-generator/**"
      - "skyscrapers-core/**"
      - "skyscrapers-solver/**"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - name: Install wasm-pack
        uses: taiki-e/install-action@3235f8901fd37ffed0052b276cec25a362fb82e9 # v2.77.7
        with:
          tool: wasm-pack@0.14.0
      - name: Build WASM package
        run: wasm-pack build --target web skyscrapers-generator
      - name: Set up Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: lts/*
          cache: "npm"
          cache-dependency-path: |
            skyscrapers-player/package-lock.json
            skyscrapers-web/package-lock.json
      - name: Install player dependencies
        working-directory: skyscrapers-player
        run: npm ci
      - name: Player lint
        working-directory: skyscrapers-player
        run: npm run lint
      - name: Player format check
        working-directory: skyscrapers-player
        run: npm run format:check
      - name: Player typecheck
        working-directory: skyscrapers-player
        run: npm run typecheck
      - name: Player test
        working-directory: skyscrapers-player
        run: npm run test
      - name: Install web dependencies
        working-directory: skyscrapers-web
        run: npm ci
      - name: Web lint
        working-directory: skyscrapers-web
        run: npm run lint
      - name: Web format check
        working-directory: skyscrapers-web
        run: npm run format:check
      - name: Web test
        working-directory: skyscrapers-web
        run: npm run test
      - name: Web build
        working-directory: skyscrapers-web
        run: npm run build
